service: watchlist-bot

frameworkVersion: '2'

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  lambdaHashingVersion: '20201221'

  stage: prod
  apiName: ${self:service}--${opt:stage, self:provider.stage}

  environment:
    PUBLIC_KEY: ${env:PUBLIC_KEY}
    CLIENT_SECRET: ${env:CLIENT_SECRET}
    CLIENT_ID: ${env:CLIENT_ID}
    APPLICATION_ID: ${env:APPLICATION_ID}
    GUILD_ID: ${env:GUILD_ID}
    SA_CLIENT_EMAIL: ${env:SA_CLIENT_EMAIL}
    SA_PROJECT_ID: ${env:SA_PROJECT_ID}
    SA_PRIVATE_KEY: ${env:SA_PRIVATE_KEY}

functions:
  api:
    handler: handler.api
    events:
      - httpApi:
          path: '*'
          method: '*'
